export const SET_ACCOUNT = 'SET_ACCOUNT';

//POOL ACTIONS
export const POOL_SET_POOL_INFO = 'POOL_SET_POOL_INFO';
export const POOL_SET_STAKE_TOKEN_INFO = 'POOL_SET_STAKE_TOKEN_INFO';
export const POOL_APPROVE_TOKEN = 'POOL_APPROVE_TOKEN';